language: php

sudo: false

php:
    - 7.1
    - 7.2
    - 7.3

before_script:
    - travis_retry composer self-update
    - travis_retry composer update --prefer-source --no-interaction --no-suggest

script:
    - mkdir -p build/logs
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar; fi
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
